### ISSUE TITLE
Can't find electron-devtools-installer in packaged app

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/gh-notifications-snoozer#117]
When I run `npm run build-macos` and run the resulting GHSnooze.app, this error appears:

![screen shot 2016-11-21 at 10 14 37 am](https://cloud.githubusercontent.com/assets/82317/20490350/56ce50ba-afd3-11e6-9582-5adab1399967.png)

I think maybe we're always initializing the devtools stuff and we shouldn't. Conversely, we could move it from devDependencies to dependencies in package.json, but it seems like the kind of thing we don't want in the final product.

/cc @probablycorey

**Comment by shayfrendt** [comment]
As a data point from running this on a different machine, I'm hitting this too. 😅
