### ISSUE TITLE
All edit buttons on Filters lead to same filter

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/gh-notifications-snoozer#122]
Steps to reproduce:

1. Have a filter selected in the Tasks tab. Click the Edit link under the filter select menu.
1. Save the filter, returning to the Tasks tab.
1. Switch to the Filters tab.
1. Each pencil button takes you to the same filter you edited via the Edit link under Tasks.

/cc @probablycorey can you reproduce this?

**Comment by probablycorey** [comment]
Ick, I can reproduce this.
