### ISSUE TITLE
Make file names consistent

### ISSUE THREAD

**Issue by probablycorey** [cheshire137/gh-notifications-snoozer#22]
How do you feel about this convention:
1. If the file exports a class, the file's name should be Capitalized and camelCased like the class. Example: `class App` is in `App.js`
2. If the file exports a function, it should not be capitalized but should be camelCased like that function. Example: `module.exports = function wowMan() {` is in `wowMan.js`

???

**Comment by cheshire137** [comment]
This suits me. 👍
