### ISSUE TITLE
Add options to select multiple tasks at once

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/gh-notifications-snoozer#65]
Like in Gmail:

![gmail-select-options](https://cloud.githubusercontent.com/assets/82317/18414646/3555bf7c-7798-11e6-9b97-aaab608872ea.png)

Could have a select box that toggles your selection. Provide a menu with extra select options, like select all issues, all closed issues, all PRs, all merged PRs, etc. Available options could be based on the tasks currently shown.

**Comment by probablycorey** [comment]
We had this, then @cheshire137 and I thought we should get rid of it. It's gone as of https://github.com/cheshire137/gh-notifications-snoozer/pull/116.
