### ISSUE TITLE
Do something with an empty task list

### ISSUE THREAD

**Issue by summasmiff** [cheshire137/gh-notifications-snoozer#66]
If a filter turns up no results, show something like "Nothing to see here" or a suggestion to better refine the search.

**Comment by cheshire137** [comment]
Or even something congratulatory, like "you've reached the end, no more GitHub tasks!".

Here's how it currently looks:

![screen shot 2016-09-11 at 4 45 41 pm](https://cloud.githubusercontent.com/assets/82317/18420743/44a1e756-783f-11e6-9628-4055250e2543.png)
