### ISSUE TITLE
Fix EventEmitter memory leak

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/gh-notifications-snoozer#77]
This error appears in the shell while the app is running:

> (node:82691) Warning: Possible EventEmitter memory leak detected. 11 title listeners added. Use emitter.setMaxListeners() to increase limit

I think it's something to do with our calls like `ipcRenderer.send('title', 'Authenticate')` to set the window title.

**Comment by probablycorey** [comment]
I don't see this bug anymore. If it shows up again we can reopen it!
