### ISSUE TITLE
Don't include Bulma library directly

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/gh-notifications-snoozer#82]
This is a minor thing, but it bugs me. GitHub lists this project as a CSS project because the Bulma CSS library is such a large file that it overshadows the JavaScript in this repo.

![screen shot 2016-09-26 at 11 12 09 am](https://cloud.githubusercontent.com/assets/82317/18842290/2c4052aa-83da-11e6-8f95-a1da3910a8c2.png)

We could pull in Bulma from a CDN, which might not be desirable since this is a standalone app and not a web site. We could also probably include Bulma via an npm package.

**Comment by summasmiff** [comment]
I don't see any reason we shouldn't use a CDN. We already require a internet connection for the fetching of notifications, so the app isn't really something that could ever be used offline.

**Comment by zeke** [comment]
Slightly off-topic: Are you liking Bulma?

**Comment by cheshire137** [comment]
I do like Bulma! I've used it for a couple projects now and it has stayed out of my way while providing useful utilities. I really like the column system with how you can just omit the sizes by default and it will make them all equal width. I like trying new CSS frameworks but I don't often stick to them for more than one project because they end up being more hassle than they're worth, or they don't have enough to handle all my use cases. I think Bulma is the only one I've really stuck with besides Bootstrap.

https://github.com/cheshire137/soma-chrome is another project of mine using Bulma.
