### ISSUE TITLE
Get rid of horizontal scrollbar in hidden tasks view

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/gh-notifications-snoozer#84]
Long filter names can cause the left column to have a horizontal scrollbar:

![screen shot 2016-09-27 at 4 47 29 pm](https://cloud.githubusercontent.com/assets/82317/18893127/26e931ca-84d2-11e6-85d6-fb85a4f015ec.png)

I think using a class like `is-three-quarters` from Bulma -- see http://bulma.io/documentation/grid/columns/ -- will fix the horizontal scrollbar.

**Comment by mattxwang** [comment]
I might be looking at this issue wrong (let me know if I am), but if you just don't want to have a scrollbar, you can give the element a width and `overflow-x:none;`. More info [here](http://www.w3schools.com/cssref/css3_pr_overflow-x.asp). In addition, you can force the text to wrap if you have a fixed-width element (e.g. the filter name div) using `word-wrap: break-word;`. [Here](http://stackoverflow.com/questions/5120313/wrapping-the-text-inside-div-css) is a good StackOverflow question explaining how to use it.

Good luck!

**Comment by cheshire137** [comment]
Setting `overflow-x: none` would remove the scrollbar, but we have a little more horizontal real estate that we're not using well right now. The top area is split 50/50 between the title area that's getting cut off and a single button on the right. The button on the right doesn't need as much room as it's got right now, while the title area could use it so we don't have to 1) cut the text off or 2) force wrapping. 👍
