### ISSUE TITLE
Buttons stay enabled when nothing selected in view

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/gh-notifications-snoozer#85]
Steps to reproduce:
1. Select a visible task.
2. Hit Snooze.
3. Click 'View hidden.'
4. Select the task again.
5. Hit Restore.
6. Click 'Tasks'.

Expected: No tasks would be selected and Snooze/Archive/Ignore would be disabled.

Actual: Observe no tasks are selected but Snooze/Archive/Ignore are enabled.

**Comment by s4kh** [comment]
Followed all the steps, but it seems working on Ubuntu.

**Comment by cheshire137** [comment]
@jgrowl, would you be willing to set up the app on your Linux machine and try to reproduce this bug?

**Comment by jgrowl** [comment]
@cheshire137 Actual behavior matches expected behavior on my Ubuntu 14.04 box. No problem from what I can see.

**Comment by cheshire137** [comment]
I just tried this again in macOS and it works here, too. So something fixed this between 15 days ago and 8 days ago -- ¯\_(ツ)_/¯.

Thanks @S4KH and @jgrowl!
