### ISSUE TITLE
Trying it out

### ISSUE THREAD

**Issue by zeke** [cheshire137/gh-notifications-snoozer#89]
:wave:

I saw the awesome new screenshot on the readme, and wanted to give this thing another go. It looks like the styles are not working though:

![screen shot 2016-09-30 at 10 13 19 am](https://cloud.githubusercontent.com/assets/2289/19000282/970fb656-86f6-11e6-8708-4fed186147e1.png)

I tried running `npm run style && npm start`, but it didn't seem to have an effect. Am I doing it wrong?

**Comment by cheshire137** [comment]
`npm run style` just runs the linter to ensure a consistent code style. Doing `npm install` and `npm start` should be sufficient for running the app. The electron-prebuilt-compile package should be compiling the LESS into CSS on the fly. 😕 

If you comment out `mainWindow.webContents.openDevTools()` in src/main.js and run the app, do you see any errors in the console?

**Comment by zeke** [comment]
No errors, neither in the browser window nor the main process.

<img width="1123" alt="screen shot 2016-10-01 at 9 27 45 pm" src="https://cloud.githubusercontent.com/assets/2289/19018607/fca867ec-881d-11e6-8385-2b1753d5ff18.png">

**Comment by cheshire137** [comment]
Any thoughts on this one @probablycorey?

**Comment by cheshire137** [comment]
If you change something in App.less and reload the app (have the developer tools open and focused, hit Cmd-R), do you get styles?

**Comment by probablycorey** [comment]
I always resort to `rm -rf node_modules && npm install` for problems like this.

**Comment by zeke** [comment]
`rm -rf node_modules && npm install` good call! 🎉 

![screen shot 2016-10-03 at 4 04 33 pm](https://cloud.githubusercontent.com/assets/2289/19057221/1f47039c-8983-11e6-9912-5510954dc3f6.png)
