### ISSUE TITLE
Add menu option to open dev tools

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/gh-notifications-snoozer#90]
We have `// mainWindow.webContents.openDevTools()` in src/main.js because it's convenient to run the app with the developer console open while debugging. It'd be nicer if we could remove that line altogether and just provide a menu option in src/models/AppMenu.js to open the console.

**Comment by darrylpargeter** [comment]
Hey @cheshire137, 
is anyone currently working on this issue? if no one is would it be possible to do it?

**Comment by cheshire137** [comment]
Have at it! :) It's all yours.

**Comment by darrylpargeter** [comment]
Thank you =]

Though quick question are you wanting the menu option appearing within one of the already established menu options or within its own e.g Tools?

**Comment by cheshire137** [comment]
Probably a new menu, File/Edit/Help don't seem to fit with this option. I think Tools or View sounds good.
